version: "{build}-{branch}"
skip_tags: true
shallow_clone: true
build: false
environment:
  global:
    # use a short path prefix to avoid running into path-length limitations
    STACK_ROOT: C:\sr
  matrix:
  - STACK_YAML: stack.yaml
platform:
  - x64
cache:
- "%STACK_ROOT%"
- .stack-work

install:
 - set PATH=%CD%\_stack;C:\msys64\usr\bin;%PATH%
 - set PATH=C:\Users\appveyor\AppData\Roaming\local\bin\;%PATH%
 - curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
 - 7z x stack.zip stack.exe > nul
 - stack setup > nul
 - stack build alex happy --fast
 - stack --no-terminal test --only-dependencies -j 1 --fast
 - stack install --fast

test_script:
- chcp 65001
- stack --no-terminal test --fast
- futhark test --no-terminal -t tests examples
